### ISSUE TITLE
Unhandled ya_activity.ApiException when destroying activity after unsuccessful ssh check

### ISSUE THREAD

**Issue by lucekdudek** [golemfactory/ray-on-golem#120]
```bash
Traceback (most recent call last):
  File "/home/lucjan/Repos/golem-ray/ray_on_golem/server/services/golem/golem.py", line 278, in _create_activity_retry
    return await self._create_activity(
  File "/home/lucjan/Repos/golem-ray/ray_on_golem/server/services/golem/golem.py", line 311, in _create_activity
    await activity.destroy()
  File "/home/lucjan/Repos/golem-core-python/golem/resources/base.py", line 60, in wrapper
    return await f(*args, **kwargs)
  File "/home/lucjan/Repos/golem-core-python/golem/resources/activity/activity.py", line 90, in destroy
    await self.api.destroy_activity(self.id)
  File "/home/lucjan/Repos/golem-ray/.venv/lib/python3.10/site-packages/ya_activity/api_client.py", line 205, in __call_api
    raise e
  File "/home/lucjan/Repos/golem-ray/.venv/lib/python3.10/site-packages/ya_activity/api_client.py", line 193, in __call_api
    response_data = await self.request(
  File "/home/lucjan/Repos/golem-ray/.venv/lib/python3.10/site-packages/ya_activity/rest.py", line 248, in DELETE
    return await self.request(
  File "/home/lucjan/Repos/golem-ray/.venv/lib/python3.10/site-packages/ya_activity/rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_activity.exceptions.ApiException: (408)
```

**Comment by lucekdudek** [comment]
Also affects https://github.com/golemfactory/ray-on-golem/blob/0.4.1/ray_on_golem/server/services/ray.py#L154C3-L161
